# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(default='nombre_doc', max_length=200)),
                ('apellidopat_doc', models.CharField(default='apellido_doc', max_length=200)),
                ('apellidomat_doc', models.CharField(default='apellido_doc', max_length=200)),
                ('correo_doc', models.EmailField(max_length=100)),
                ('edad', models.IntegerField()),
                ('titulos', models.TextField()),
                ('cedulatitulacion', models.CharField(max_length=100)),
                ('Doctor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('codigopostal', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
