# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nombre_doc', models.CharField(blank=True, default='nombre_doc', max_length=100, null=True)),
                ('apellidopat_doc', models.CharField(blank=True, default='apellido_doc', max_length=100, null=True)),
                ('apellidomat_doc', models.CharField(blank=True, default='apellido_doc', max_length=100, null=True)),
                ('titulos', models.TextField(blank=True, null=True)),
                ('cedulatitulacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Doctor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('cuentabancaria', models.IntegerField(blank=True, null=True)),
                ('numerotelefono', models.IntegerField(blank=True, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('codigopostal', models.IntegerField(blank=True, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.IntegerField()),
                ('cotenido', models.IntegerField()),
                ('imagen', models.CharField(max_length=100)),
                ('fechapublicacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_fundacion', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Nombre',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='doctor',
            name='idFundacion_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hospital'),
        ),
    ]
