# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171130_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_doctor',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_fundacion',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_hospital',
            field=models.NullBooleanField(default=False),
        ),
    ]
